### ISSUE TITLE
loader

### ISSUE THREAD

**Issue by uf0** [C2DH/gsb-100#33]

**Comment by uf0** [comment]
- [ ] icons
- [ ] check loader on different pages

**Comment by giorgiouboldi** [comment]
![802](https://user-images.githubusercontent.com/2106518/92001452-fc9b1a80-ed3e-11ea-8449-946c7922329f.png)
![Uploading 807.png…]()

**Comment by giorgiouboldi** [comment]
![807](https://user-images.githubusercontent.com/2106518/92001522-12104480-ed3f-11ea-99d7-196b8d3a213c.png)

**Comment by giorgiouboldi** [comment]
![802](https://user-images.githubusercontent.com/2106518/92001545-189ebc00-ed3f-11ea-8aa4-ad2719778d6c.png)
