### ISSUE TITLE
missing events

### ISSUE THREAD

**Issue by uf0** [C2DH/gsb-100#52]
- [x] Welche Kriegserlebnisse?
- [x] Propaganda, Einflussnahme oder harmlose Unterstützung?
- [x] Welche Auswirkungen hat ein Staatenwechsel?
- [x] Was steckt in einem Namen?

**Comment by danieleguido** [comment]
Added using 
```sh
docker exec -it gsb-100-stack_miller_1  python manage.py add_documents_to_story <story-pk> [ ... <document-slug> ]
```
example: 
```sh
docker exec -it gsb-100-stack_miller_1  python manage.py add_documents_to_story 74 ArrondissementMalmedy AngliederunganPreussen
```

**Comment by danieleguido** [comment]
Duplicate event in spreadsheet: "DeutschOstbelgien" is present twice
